firstName=input("Enter Your First Name: ").strip().capitalize()
midName=input("Enter Your Mid Name: ").strip().capitalize()
lastName=input("Enter Your Last Name: ").strip().capitalize()
email=input("Enter Your Email: ").strip()
print(f"Welcome {firstName} {midName:.1s} {lastName}")
print(f"Your Domain is: {email[:email.index('@')]} and website is {email[email.index('@')+1:]}")
